import{S as A,i as k}from"./assets/vendor-46aac873.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const r of o.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerpolicy&&(o.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?o.credentials="include":e.crossorigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const O="/goit-js-hw-11/assets/dang-75a3a476.svg",D="/goit-js-hw-11/assets/err-d9947029.svg",S="/goit-js-hw-11/assets/x-a193917d.svg",I=new A(".gallery a",{captionDelay:250,captionsData:"alt"}),C=document.querySelector(".form"),l=document.querySelector(".gallery");C.addEventListener("submit",n=>{n.preventDefault(),l.innerHTML='<span class="loader"></span>',V(n).then(t=>$(t)).catch(t=>P(t)),C.reset()});function V({target:{keyword:{value:n}}}){const t="https://pixabay.com",s="/api",a=new URLSearchParams({key:"42096263-920755fbf423cd5814494514c",q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${t}${s}?${a}`).then(e=>{if(e.ok)return e.json();throw new Error(`${e.status} - ${e.statusText}`)})}function $({totalHits:n,hits:t}){if(parseInt(n)>0){const s=t.map(T);l.innerHTML="",l.append(...s),I.refresh()}else l.innerHTML="",v()}function v(){k.warning({title:"Sorry,",titleColor:"#FFFFFF",message:"there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#FFA000",iconUrl:O,position:"center",close:!1,buttons:[[`<button type="button" style="
          background-color: #FFA000; 
          width: 20px; 
          height: 20px; 
          padding: 5px">
            <img style="
              width: 10px; 
              height: 10px" 
              src=${S}>
        </button>`,function(n,t){n.hide({transitionOut:"fadeOut"},t)}]]})}function P(n){k.show({title:"Error",titleColor:"#FFFFFF",message:`${n}`,messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:D,position:"topRight",close:!1,buttons:[[`<button type="button" style="
          background-color: #EF4040; 
          width: 20px; 
          height: 20px; 
          padding: 5px">
            <img style="
              width: 10px; 
              height: 10px" 
                src=${S}>
        </button>`,function(t,s){t.hide({transitionOut:"fadeOut"},s)}]]})}function T({webformatURL:n,largeImageURL:t,tags:s,likes:a,views:e,comments:o,downloads:r}){const d=document.createElement("ul");d.classList.add("card");const i=document.createElement("a");i.classList.add("gallery-link"),i.setAttribute("href",t);const c=document.createElement("img");c.classList.add("gallery-image"),c.setAttribute("src",n),c.setAttribute("alt",s);const m=document.createElement("ul");m.classList.add("item-img");const u=document.createElement("li");u.classList.add("elem-img");const p=document.createElement("p");p.classList.add("elem-name"),p.textContent="Likes";const x=document.createElement("p");x.textContent=a;const g=document.createElement("li");g.classList.add("elem-img");const f=document.createElement("p");f.classList.add("elem-name"),f.textContent="Views";const E=document.createElement("p");E.textContent=e;const h=document.createElement("li");h.classList.add("elem-img");const y=document.createElement("p");y.classList.add("elem-name"),y.textContent="Comments";const b=document.createElement("p");b.textContent=o;const F=document.createElement("li");F.classList.add("elem-img");const L=document.createElement("p");L.classList.add("elem-name"),L.textContent="Downloads";const w=document.createElement("p");return w.textContent=r,F.append(L,w),h.append(y,b),g.append(f,E),u.append(p,x),m.append(u,g,h,F),i.append(c),d.append(i,m),d}
//# sourceMappingURL=commonHelpers.js.map
