import{S as A,i as k}from"./assets/vendor-46aac873.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const r of t.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&a(r)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const O="/goit-js-hw-11/assets/dang-75a3a476.svg",D="/goit-js-hw-11/assets/err-d9947029.svg",S="/goit-js-hw-11/assets/x-a193917d.svg",I=new A(".gallery a",{captionDelay:250,captionsData:"alt"}),C=document.querySelector(".form"),l=document.querySelector(".gallery");C.addEventListener("submit",o=>{o.preventDefault(),l.innerHTML='<span class="loader"></span>',V(o).then(n=>$(n)).catch(n=>P(n)),C.reset()});function V({target:{keyword:{value:o}}}){const n="https://pixabay.com",s="/api",a=new URLSearchParams({key:"42096263-920755fbf423cd5814494514c",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}),e=`${n}${s}?${a}`;return fetch(e).then(t=>{if(t.ok)return t.json();throw new Error(`${t.status} - ${t.statusText}`)})}function $({totalHits:o,hits:n}){if(parseInt(o)>0){const s=n.map(R);l.innerHTML="",l.append(...s),I.refresh()}else l.innerHTML="",v()}function v(){k.warning({title:"Sorry,",titleColor:"#FFFFFF",message:"there are no images matching your search query. Please try again!",messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#FFA000",iconUrl:O,position:"center",close:!1,buttons:[[`<button type="button" style="
          background-color: #FFA000; 
          width: 20px; 
          height: 20px; 
          padding: 5px">
            <img style="
              width: 10px; 
              height: 10px" 
              src=${S}>
        </button>`,function(o,n){o.hide({transitionOut:"fadeOut"},n)}]]})}function P(o){k.show({title:"Error",titleColor:"#FFFFFF",message:`${o}`,messageColor:"#FFFFFF",messageSize:"16px",backgroundColor:"#EF4040",iconUrl:D,position:"topRight",close:!1,buttons:[[`<button type="button" style="
          background-color: #EF4040; 
          width: 20px; 
          height: 20px; 
          padding: 5px">
            <img style="
              width: 10px; 
              height: 10px" 
                src=${S}>
        </button>`,function(n,s){n.hide({transitionOut:"fadeOut"},s)}]]})}function R({webformatURL:o,largeImageURL:n,tags:s,likes:a,views:e,comments:t,downloads:r}){const d=document.createElement("ul");d.classList.add("card");const i=document.createElement("a");i.classList.add("gallery-link"),i.setAttribute("href",n);const c=document.createElement("img");c.classList.add("gallery-image"),c.setAttribute("src",o),c.setAttribute("alt",s);const m=document.createElement("ul");m.classList.add("item-img");const u=document.createElement("li");u.classList.add("elem-img");const p=document.createElement("p");p.classList.add("elem-name"),p.textContent="Likes";const x=document.createElement("p");x.textContent=a;const g=document.createElement("li");g.classList.add("elem-img");const f=document.createElement("p");f.classList.add("elem-name"),f.textContent="Views";const E=document.createElement("p");E.textContent=e;const h=document.createElement("li");h.classList.add("elem-img");const y=document.createElement("p");y.classList.add("elem-name"),y.textContent="Comments";const b=document.createElement("p");b.textContent=t;const F=document.createElement("li");F.classList.add("elem-img");const L=document.createElement("p");L.classList.add("elem-name"),L.textContent="Downloads";const w=document.createElement("p");return w.textContent=r,F.append(L,w),h.append(y,b),g.append(f,E),u.append(p,x),m.append(u,g,h,F),i.append(c),d.append(i,m),d}
//# sourceMappingURL=commonHelpers.js.map
